let catalogo = [
    {
        id: 0,
        nombre: "Lámpara Pop",
        precio: 900,
        descripcion: "Lámpara de mesa retro con acabado brillante y diseño compacto.",
        categoria: "Lamparas",
        colores: ["Naranja", "Azul"],
        disponibilidad: 12,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: true,
        etiquetas: ["Retro", "Decorativo"],
        imagenes: ["img/LAMPARAS/LamparaPop/N_V1.png","img/LAMPARAS/LamparaPop/N_V2.png","img/LAMPARAS/LamparaPop/A_V1.png", "img/LAMPARAS/LamparaPop/A_V2.png"]

    },
    {
        id: 1,
        nombre: "Sillón Urban Steel",
        precio: 7500,
        descripcion: "Sillón contemporáneo con estructura tubular cromada.",
        categoria: "Sillones",
        colores: ["Azul", "Marron"],
        disponibilidad: 9,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: false,
        etiquetas: ["Moderno", "Minimalista"],
        imagenes: ["img/SILLONES/SillónUrbanSteel/A_V1.png","img/SILLONES/SillónUrbanSteel/A_V2.png","img/SILLONES/SillónUrbanSteel/M_V1.png","img/SILLONES/SillónUrbanSteel/M_V2.png"]
    },
    {
        id: 2,
        nombre: "Reloj Flip Retro",
        precio: 1300,
        descripcion: "Reloj de mesa con mecanismo de tarjetas abatibles.",
        categoria: "Relojes",
        colores: ["Negro", "Plateado"],
        disponibilidad: 8,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: false,        
        etiquetas: ["Retro", "Clasico"],
        imagenes: ["img/RELOJES/RelojFlipRetro/N_V1.png","img/RELOJES/RelojFlipRetro/M_V1.png"]
    },
    {
        id: 3,
        nombre: "Lámpara Dome",
        precio: 1250,
        descripcion: "Lámpara moderna con pantalla semiesférica y base cilíndrica.",
        categoria: "Lamparas",
        colores: ["Verde", "Rosa"],
        disponibilidad: 2,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: false,        
        etiquetas: ["Moderno", "Minimalista", "Decorativo"],
        imagenes: ["img/LAMPARAS/LámparaDome/V_V1.png","img/LAMPARAS/LámparaDome/R_V1.png"]
    },
    {
        id: 4,
        nombre: "Reloj Loop",
        precio: 500,
        descripcion: "Reloj de pared moderno con marco abierto y detalles en madera.",
        categoria: "Relojes",
        colores: ["Negro", "Rojo", "Marron"],
        disponibilidad:  5,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: false,        
        etiquetas: ["Moderno", "Minimalista"],
        imagenes: ["img/RELOJES/RelojLoop/N_V1.png","img/RELOJES/RelojLoop/M_V1.png","img/RELOJES/RelojLoop/R_V1.png"]
    },
    {
        id: 5,
        nombre: "Sillón Verona",
        precio: 8200,
        descripcion: "Sillón curvo tapizado en tela suave.",
        categoria: "Sillones",
        colores: ["Verde", "Beige"],
        disponibilidad:  6,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: false,        
        etiquetas: ["Moderno", "Decorativo"],
        imagenes: ["img/SILLONES/SillónVerona/V_V1.png","img/SILLONES/SillónVerona/V_V2.png","img/SILLONES/SillónVerona/B_V1.png","img/SILLONES/SillónVerona/B_V2.png"]
    },
    {
        id: 6,
        nombre: "Lámpara Chrome",
        precio: 800,
        descripcion: "Diseño futurista con acabado cromado.",
        categoria: "Lamparas",
        colores: ["Celeste", "Negro"],
        disponibilidad: 15,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: false,        
        etiquetas: ["Moderno", "Minimalista"],
        imagenes: ["img/LAMPARAS/LamparaChrome/V_V1.png","img/LAMPARAS/LamparaChrome/N_V1.png"]
    },
    {
        id: 7,
        nombre: "Reloj Flor",
        precio: 450,
        descripcion: "Reloj de pared con diseño floral y acabado suave.",
        categoria: "Relojes",
        colores: ["Beige", "Verde", "Rojo"],
        disponibilidad:  2,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: false,        
        etiquetas: ["Orgánico ", "Decorativo"],
        imagenes: ["img/RELOJES/Reloj Flor/B_V1.png","img/RELOJES/Reloj Flor/R_V1.png"]
    },
    {
        id: 8,
        nombre: "Lámpara Blush",
        precio: 750,
        descripcion: "Lámpara elegante de líneas suaves.",
        categoria: "Lamparas",
        colores: ["Rosa", "Beige", "Rosa"],
        disponibilidad:  10,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: true,        
        etiquetas: ["Minimalista", "Decorativo"],
        imagenes: ["img/LAMPARAS/LamparaBlush/Ro_V1.png","img/LAMPARAS/LamparaBlush/B_V1.png","img/LAMPARAS/LamparaBlush/V_V1.png"]
    },
    {
        id: 9,
        nombre: "Reloj Dona",
        precio: 860,
        descripcion: "Reloj de pared de colores intensos.",
        categoria: "Relojes",
        colores: ["Amarillo", "Rojo"],
        disponibilidad: 10,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: true,        
        etiquetas: ["Moderno", "Decorativo"],
        imagenes: ["img/RELOJES/RelojDona/A_V1.png","img/RELOJES/RelojDona/R_V1.png"]
    },
    {
        id: 10,
        nombre: "Lámpara Shade",
        precio: 780,
        descripcion: "Lámpara clásica con pantalla textil.",
        categoria: "Lamparas",
        colores: ["Celeste", "Naranja"],
        disponibilidad: 14,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: false,        
        etiquetas: ["Clasico", "Decorativo"],
        imagenes: ["img/LAMPARAS/LámparaSkyShade/C_V1.png","img/LAMPARAS/LámparaSkyShade/N_V1.png"]
    },
    {
        id: 11,
        nombre: "Sillón Cloud",
        precio: 6400,
        descripcion: "Diseño redondeado con base giratoria y gran comodidad.",
        categoria: "Sillones",
        colores: ["Beige"],
        disponibilidad: 11,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: false,        
        etiquetas: ["Moderno", "Minimalista"],
        imagenes: ["img/SILLONES/SillónCloud/V1.png","img/SILLONES/SillónCloud/V2.png"]
    },
    {
        id: 12,
        nombre: "Reloj Melt",
        precio: 650,
        descripcion: "Reloj de pared con forma orgánica y diseño contemporáneo.",
        categoria: "Relojes",
        colores: ["Verde", "Rojo"],
        disponibilidad: 11,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: false,        
        etiquetas: ["Orgánico ", "Moderno"],
        imagenes: ["img/RELOJES/RelojMelt/R_V1.png","img/RELOJES/RelojMelt/V_V1.png"]
    },
    {
        id: 13,
        nombre: "Lámpara Disc",
        precio: 670,
        descripcion: "Lámpara de escritorio con diseño minimalista.",
        categoria: "Lamparas",
        colores: ["Amarillo", "Rojo"],
        disponibilidad: 9,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: true,        
        etiquetas: ["Minimalista", "Moderno"],
        imagenes: ["img/LAMPARAS/LámparaDisc/A.png","img/LAMPARAS/LámparaDisc/R_V1.png"]
    },
    {
        id: 14,
        nombre: "Reloj Flip",
        precio: 1300,
        descripcion: "Reloj retro de sobremesa con números abatibles.",
        categoria: "Relojes",
        colores: ["Naranja"],
        disponibilidad: 3,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: false,        
        etiquetas: ["Retro", "Clasico"],
        imagenes: ["img/RELOJES/RelojFlip/N_1.png"]
    },
    {
        id: 15,
        nombre: "Sillón Organic",
        precio: 8400,
        descripcion: "Sillón escultórico con formas orgánicas y base de madera.",
        categoria: "Sillones",
        colores: ["Beige","Verde"],
        disponibilidad: 7,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: false,        
        etiquetas: ["Orgánico ", "Decorativo"],
        imagenes: ["img/SILLONES/SillónOrganic/V_V1.png","img/SILLONES/SillónOrganic/V_V2.png","img/SILLONES/SillónOrganic/B_V1.png","img/SILLONES/SillónOrganic/B_V2.png"]
    },
    {
        id: 16,
        nombre: "Lámpara Ruby Wave",
        precio: 1320,
        descripcion: "Lámpara escultórica con base ondulada y acabado brillante.",
        categoria: "Lamparas",
        colores: ["Rojo", "Verde"],
        disponibilidad:  2,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: false,        
        etiquetas: ["Orgánico ", "Decorativo"],
        imagenes: ["img/LAMPARAS/LámparaRubyWave/R_V1.png","img/LAMPARAS/LámparaRubyWave/V_V1.png"]
    },
    {
        id: 17,
        nombre: "Reloj Navigator Classic",
        precio: 860,
        descripcion: "Reloj rectangular con estilo industrial y elegante.",
        categoria: "Relojes",
        colores: ["Negro"],
        disponibilidad: 13,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: false,        
        etiquetas: ["Moderno", "Clasico"],
        imagenes: ["img/RELOJES/RelojNavigatorClassic/N_1.png"]
    },
    {
        id: 18,
        nombre: "Sillón Retro Forest",
        precio: 8700,
        descripcion: "Sillón de inspiración vintage con estructura de madera vista.",
        categoria: "Sillones",
        colores: ["Verde"],
        disponibilidad: 8,
        stockAviso: 3,
        fechaFinDescuento: "2026-06-30",
        enTemporada: true,        
        etiquetas: ["Retro", "Clasico"],
        imagenes: ["img/SILLONES/SillónRetroForest/V1.png","img/SILLONES/SillónRetroForest/V2.png"]
    }
];
